#!/bin/sh
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . Room.java Light.java host.java

echo "---------------------------------------------------------"

echo "Execute Project"
echo "sudo java -classpath .:classes:/opt/pi4j/lib/'*'  Room.java Light.java host.java"
